services:
  screenshot-service:
    build: .
    volumes:
      - ./screenshots:/vm/screenshots
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=screenshot_api.py
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3